name: XML Validation
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  validate-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
                
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Validate XML against XSD
        run: |
          errors=0
          for file in $(find . -name "*.sbc"); do
            echo "Validating $file"
            if ! xmllint --noout "$file"; then
              echo "Error in $file"
              errors=$((errors + 1))
            fi
          done
          if [ "$errors" -ne 0 ]; then
            echo "$errors SBC files failed validation"
            exit 1
          else
            echo "All SBC files validated successfully"
          fi
